name: Deploy Spring Boot Docker to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2   # Cambia a tu regiÃ³n

    - name: Get EC2 Public IP
      id: ec2ip
      run: |
        IP=$(aws ec2 describe-instances \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text)
        echo "EC2_IP=$IP" >> $GITHUB_ENV

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t todo-list-app .

    - name: Save Docker image
      run: docker save todo-list-app | gzip > todo-list-app.tar.gz

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "todo-list-app.tar.gz"
        target: "/home/ubuntu/"

    - name: Load and run container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load < todo-list-app.tar.gz
          docker stop todo-list-app || true
          docker rm todo-list-app || true
          docker run -d --name todo-list-app -p 8080:8080 todo-list-app

    - name: Cleanup
      run: rm -f private_key